/* platform/esp32_idf/main/bsp_esp32_pwm.h
 *
 * Slot-indexed LEDC PWM wrapper.  Each fan slot (0 ..
 * THERMAL_MAX_ACTUATORS-1) drives an independent LEDC channel
 * (slot N -> LEDC_CHANNEL_<N>).  All slots share LEDC_TIMER_0,
 * so all fans run at the same PWM frequency (v1 simplification;
 * mixed-frequency would need per-fan timer allocation).
 *
 * 8-bit duty resolution (0..255).  Pin assignments come from
 * `G_ESP32_PINMAP` (see esp32_pinmap.h), which is generated by
 * json2static.py from the JSON config.
 */
#ifndef BSP_ESP32_PWM_H
#define BSP_ESP32_PWM_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Configure the LEDC timer (first call only) + the per-slot
 * channel for `gpio_num` at `freq_hz`.  Subsequent calls re-use
 * LEDC_TIMER_0 -- pass a consistent `freq_hz` across slots (v1).
 *
 * Returns 0 on success, -1 if `slot >= THERMAL_MAX_ACTUATORS` or
 * an IDF call fails. */
int bsp_esp32_pwm_init(uint8_t slot, int gpio_num, uint32_t freq_hz);

/* Apply a duty value 0..255 to the channel for `slot`.  No-op if
 * `_init(slot, ...)` was not called successfully. */
void bsp_esp32_pwm_set_duty(uint8_t slot, uint8_t duty_0_255);

#ifdef __cplusplus
}
#endif

#endif /* BSP_ESP32_PWM_H */
