/* platform/esp32_idf/main/main.c
 *
 * Stage 14 14a -- three app_main paths selected at compile time.
 *
 *   STANDALONE        (default; same as 13b):
 *     Real DS18B20 + tach + LEDC fan.  Sensor at 1 Hz, core at
 *     10 Hz, status line at 1 Hz.  Drives the bench rig.
 *
 *   REPLAY_STANDALONE (-DTHERMALCORE_REPLAY_STANDALONE=ON):
 *     No BSP init.  Walks `G_REPLAY_TICKS[]` (see
 *     replay_fixture.c), feeds each row through
 *     thermal_core_step(), lets the callbacks emit canonical
 *     CSV rows, prints `END\n`, parks.  Stage 15 uses this
 *     output for host-vs-target byte-for-byte parity.
 *
 *   HIL_PERIPHERAL    (-DTHERMALCORE_HIL_PERIPHERAL=ON):
 *     Real BSPs, no thermal_core_step() (the Linux daemon
 *     owns the control loop).  Loop reads sensor (1 Hz
 *     cached) + tach delta (10 Hz), encodes each as a
 *     TELEM_SAMPLE TC frame, writes to USB-Serial-JTAG.
 *     PWM parked at 0 duty until 14b wires the inbound
 *     CMD_REQUEST path.
 *
 * The portable `core/` source is linked unchanged in
 * STANDALONE and REPLAY.  HIL skips it (the daemon runs
 * thermal_core_step instead) but `protocol/thermal_wire.c`
 * comes in via thermal_wire_encode_telem_sample.
 * G_THERMAL_CFG is generated by tools/json2static.py from
 * configs/esp32-c3-standalone.json.
 *
 * Pin map (STANDALONE + HIL):
 *   GPIO 4 -- fan PWM out (25 kHz, 3.3 V)
 *   GPIO 5 -- fan tach in (10k pull-up to 3.3 V)
 *   GPIO 6 -- DS18B20 1-Wire data (4.7k pull-up to 3.3 V)
 *
 * See PRD section 4.2 + 8.3 and impl-plan section 5
 * Stages 13 + 14.
 */
#include <inttypes.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_log.h"
#include "esp_timer.h"

#include "bsp_esp32_pwm.h"
#include "bsp_esp32_tach.h"
#include "bsp_esp32_sensor.h"
#include "esp32_callbacks.h"

#include "thermal_core.h"
#include "thermal_types.h"
#include "thermal_signals.h"
#include "thermal_config.h"

#if defined(THERMALCORE_MODE_REPLAY_STANDALONE)
#include "replay_fixture.h"
#endif

#if defined(THERMALCORE_MODE_HIL_PERIPHERAL)
#include "esp32_usb_cdc.h"
#include "thermal_wire.h"
#include "thermal_wire_opcodes.h"
#endif

#define PIN_FAN_PWM      4
#define PIN_FAN_TACH     5
#define PIN_ONEWIRE      6
#define PWM_FREQ_HZ      25000

extern const thermal_config_t G_THERMAL_CFG;

static const char *TAG = "thermal";

#if defined(THERMALCORE_MODE_HIL_PERIPHERAL)

/* Provisional HIL ingress signal IDs.  Sit in the 0x0700+ gap
 * above the existing TSIG_* ranges (zone/actuator/PID/context/
 * modifier/fault all live in 0x0100..0x06FF).  14c will promote
 * these into core/thermal_signals.h once the daemon-side
 * dispatcher lands. */
#define HIL_SIG_SENSOR_TEMP_0  0x0701u
#define HIL_SIG_TACH_RPM_0     0x0702u

/* Platform-private command IDs (PRD section 8.3 -- 0x8000..0xFFFF
 * range).  14c expands this set; 14b ships only SET_PWM_DUTY. */
#define HIL_CMD_SET_PWM_DUTY   0x8001u

/* Sized for a worst-case inbound frame plus enough headroom that
 * the sliding-window scanner doesn't constantly memmove. */
#define HIL_RX_BUF_SIZE (THERMAL_WIRE_MAX_MCU \
                         + THERMAL_WIRE_HEADER_LEN \
                         + THERMAL_WIRE_CRC_LEN)

/* === HIL inbound dispatch ================================ */

static void hil_dispatch_frame(const thermal_wire_frame_t *fr,
                                uint32_t now_ms, uint16_t *out_seq)
{
    /* ACK / NACK fit easily in this stack buffer (HEADER + 8-byte
     * ack/nack payload + CRC = 22 bytes). */
    uint8_t reply[THERMAL_WIRE_HEADER_LEN + 8u + THERMAL_WIRE_CRC_LEN];

    if (fr->opcode != THERMAL_WIRE_OP_CMD_REQUEST) {
        int n = thermal_wire_encode_cmd_nack(
            reply, sizeof(reply), (*out_seq)++, now_ms,
            fr->seq, THERMAL_WIRE_STATUS_BAD_OPCODE,
            /*detail=*/0, /*crc_enabled=*/1);
        if (n > 0) esp32_usb_cdc_write(reply, (size_t)n);
        return;
    }

    /* Payload must have at least the 2-byte command_id header
     * (PRD section 7.5 lines 968-972). */
    uint16_t command_id = 0;
    if (fr->payload_len >= 2u) {
        command_id = (uint16_t)fr->payload[0]
                   | ((uint16_t)fr->payload[1] << 8);
    }

    if (command_id == HIL_CMD_SET_PWM_DUTY && fr->payload_len == 3u) {
        uint8_t duty = fr->payload[2];
        bsp_esp32_pwm_set_duty(duty);
        int n = thermal_wire_encode_cmd_ack(
            reply, sizeof(reply), (*out_seq)++, now_ms,
            fr->seq, /*status=*/0u,
            /*detail=*/(uint32_t)duty, /*crc_enabled=*/1);
        if (n > 0) esp32_usb_cdc_write(reply, (size_t)n);
        return;
    }

    /* Anything else (unknown command_id, length mismatch, or
     * payload too short) -> NACK with BAD_PAYLOAD.  detail carries
     * the offending command_id so the host can correlate. */
    {
        int n = thermal_wire_encode_cmd_nack(
            reply, sizeof(reply), (*out_seq)++, now_ms,
            fr->seq, THERMAL_WIRE_STATUS_BAD_PAYLOAD,
            /*detail=*/(uint32_t)command_id, /*crc_enabled=*/1);
        if (n > 0) esp32_usb_cdc_write(reply, (size_t)n);
    }
}

/* Sliding-window frame accumulator.  Pulls bytes off the
 * USB-Serial-JTAG rx queue, attempts to decode frames starting
 * at offset 0, dispatches OK frames, drops 1 byte on
 * unrecoverable decoder errors (BAD_MAGIC / BAD_CRC / ...)
 * to keep the stream self-healing. */
static uint8_t s_hil_rx_buf[HIL_RX_BUF_SIZE];
static size_t  s_hil_rx_pos = 0;

static void hil_drain_commands(uint32_t now_ms, uint16_t *out_seq)
{
    /* 1. Pull whatever the driver has into the tail of the buffer. */
    size_t free_cap = sizeof(s_hil_rx_buf) - s_hil_rx_pos;
    if (free_cap > 0) {
        size_t got = esp32_usb_cdc_read(s_hil_rx_buf + s_hil_rx_pos,
                                         free_cap);
        s_hil_rx_pos += got;
    } else {
        /* Pathological: buffer full with no decodable frame at the
         * head.  Drop the oldest byte and try again next tick. */
        memmove(s_hil_rx_buf, s_hil_rx_buf + 1, s_hil_rx_pos - 1);
        s_hil_rx_pos--;
    }

    /* 2. Try to decode at offset 0 repeatedly until short or no
     *    progress.  Multiple frames per call is expected. */
    while (s_hil_rx_pos >= THERMAL_WIRE_HEADER_LEN) {
        thermal_wire_frame_t fr;
        int dec = thermal_wire_decode_frame(s_hil_rx_buf, s_hil_rx_pos,
                                            THERMAL_WIRE_MAX_MCU,
                                            /*crc_enabled=*/1, &fr);
        if (dec == THERMAL_WIRE_OK) {
            hil_dispatch_frame(&fr, now_ms, out_seq);
            size_t consumed = (size_t)THERMAL_WIRE_HEADER_LEN
                            + fr.payload_len
                            + (size_t)THERMAL_WIRE_CRC_LEN;
            memmove(s_hil_rx_buf, s_hil_rx_buf + consumed,
                    s_hil_rx_pos - consumed);
            s_hil_rx_pos -= consumed;
        } else if (dec == THERMAL_WIRE_ERR_TRUNCATED) {
            return;   /* wait for more bytes */
        } else {
            /* BAD_MAGIC / BAD_CRC / BAD_VERSION / BAD_OPCODE /
             * BAD_PAYLOAD / OVER_CAP: drop 1 byte and resync.
             * Self-healing -- eventually the scanner finds a real
             * "TC" magic. */
            memmove(s_hil_rx_buf, s_hil_rx_buf + 1, s_hil_rx_pos - 1);
            s_hil_rx_pos--;
        }
    }
}

/* === HIL_PERIPHERAL app_main ============================== */

static void app_main_hil_peripheral(void)
{
    /* Reconfigure stdio for raw binary, mute ESP_LOG.  Must run
     * before any frame is emitted -- see esp32_usb_cdc.c. */
    esp32_usb_cdc_init();

    if (bsp_esp32_pwm_init(PIN_FAN_PWM, PWM_FREQ_HZ) != 0) return;
    if (bsp_esp32_tach_init(PIN_FAN_TACH)            != 0) return;
    int sensor_ok = (bsp_esp32_sensor_init(PIN_ONEWIRE) == 0);

    /* PWM parked at 0 duty until 14b wires inbound CMD_REQUEST. */
    bsp_esp32_pwm_set_duty(0);

    int32_t  cached_temp_mc   = INT32_MIN;
    uint8_t  cached_valid     = 0;
    uint32_t now_ms           = 0;
    int      ticks_since_read = 10;     /* force a read on tick 0 */
    uint16_t seq              = 0;
    const uint16_t dt_ms      = 100;    /* same cadence as the daemon */

    uint8_t frame[THERMAL_WIRE_MAX_MCU];

    for (;;) {
        int64_t t0_us = esp_timer_get_time();

        /* Drain inbound CMD_REQUEST frames first so a duty set
         * received this tick takes effect before the next
         * outbound emission. */
        hil_drain_commands(now_ms, &seq);

        /* 1 Hz sensor refresh, same cadence as STANDALONE. */
        if (sensor_ok && ticks_since_read >= 10) {
            int32_t temp_mc;
            if (bsp_esp32_sensor_read_mc(&temp_mc) == 0) {
                cached_temp_mc = temp_mc;
                cached_valid   = 1;
            } else {
                cached_valid   = 0;
            }
            ticks_since_read = 0;
        }
        ticks_since_read++;

        uint32_t ticks = bsp_esp32_tach_read_ticks_delta();
        int32_t  rpm_q = (int32_t)(ticks * 30u);

        /* Temp sample (only when valid -- daemon treats absence
         * as no-update; the next tick will retry). */
        if (cached_valid) {
            int n = thermal_wire_encode_telem_sample(
                frame, sizeof(frame), seq++, now_ms,
                HIL_SIG_SENSOR_TEMP_0, /*flags=*/0,
                cached_temp_mc, /*crc_enabled=*/1);
            if (n > 0) esp32_usb_cdc_write(frame, (size_t)n);
        }

        /* Tach sample (always; flags=0; daemon converts to
         * thermal_sample_t with kind=TACH_RPM in 14c). */
        {
            int n = thermal_wire_encode_telem_sample(
                frame, sizeof(frame), seq++, now_ms,
                HIL_SIG_TACH_RPM_0, /*flags=*/0,
                rpm_q, /*crc_enabled=*/1);
            if (n > 0) esp32_usb_cdc_write(frame, (size_t)n);
        }

        now_ms += dt_ms;
        int64_t elapsed_us = esp_timer_get_time() - t0_us;
        int64_t remaining_us = (int64_t)dt_ms * 1000 - elapsed_us;
        if (remaining_us > 0) {
            vTaskDelay(pdMS_TO_TICKS(remaining_us / 1000));
        }
    }
}

#elif defined(THERMALCORE_MODE_REPLAY_STANDALONE)

/* === REPLAY_STANDALONE app_main (13c body, verbatim) ====== */

static void app_main_replay(void)
{
    ESP_LOGI(TAG, "thermal-core ESP32-C3 REPLAY_STANDALONE (Stage 13 13c)");

    thermal_core_t            core;
    thermal_core_callbacks_t  cb = {
        .log_event      = esp32_log_event_cb,
        .telemetry_emit = esp32_telemetry_emit_cb,
    };
    thermal_status_t init_s = thermal_core_init(&core, &G_THERMAL_CFG, &cb);
    if (init_s != THERMAL_OK) {
        ESP_LOGE(TAG, "thermal_core_init failed: %d", (int)init_s);
        return;
    }

    const uint16_t dt_ms = G_THERMAL_CFG.control_period_ms;

    for (uint16_t i = 0; i < G_REPLAY_TICK_COUNT; i++) {
        uint32_t now_ms = (uint32_t)i * (uint32_t)dt_ms;

        thermal_sample_t samples[THERMAL_MAX_SAMPLES_PER_SNAPSHOT];
        uint8_t n = 0;

        samples[n].id           = G_THERMAL_CFG.sensors[0].id;
        samples[n].kind         = THERMAL_SAMPLE_TEMP_MC;
        samples[n].sample_ts_ms = now_ms;
        samples[n].value        = G_REPLAY_TICKS[i].temp_mc;
        samples[n].valid        = 1;
        samples[n].quality      = 0;
        n++;

        samples[n].id           = G_THERMAL_CFG.actuators[0].id;
        samples[n].kind         = THERMAL_SAMPLE_TACH_RPM;
        samples[n].sample_ts_ms = now_ms;
        samples[n].value        = (int32_t)G_REPLAY_TICKS[i].tach_rpm;
        samples[n].valid        = 1;
        samples[n].quality      = 0;
        n++;

        thermal_input_snapshot_t snap = {
            .now_ms       = now_ms,
            .samples      = samples,
            .sample_count = n,
        };

        thermal_output_frame_t out;
        memset(&out, 0, sizeof(out));
        (void)thermal_core_step(&core, &snap, &out);
        /* out.actuator_cmds[] intentionally ignored -- no PWM
         * hardware to drive in REPLAY mode.  The CSV rows the
         * callbacks emitted during the step are the only
         * artefact we care about. */
    }

    printf("END\n");
    fflush(stdout);

    vTaskDelay(portMAX_DELAY);
}

#else

/* === STANDALONE app_main (13b body, verbatim) ============= */

static void app_main_standalone(void)
{
    ESP_LOGI(TAG, "thermal-core ESP32-C3 STANDALONE (Stage 13 13b)");

    if (bsp_esp32_pwm_init(PIN_FAN_PWM, PWM_FREQ_HZ) != 0) return;
    if (bsp_esp32_tach_init(PIN_FAN_TACH)            != 0) return;
    int sensor_ok = (bsp_esp32_sensor_init(PIN_ONEWIRE) == 0);

    thermal_core_t            core;
    thermal_core_callbacks_t  cb = {
        .log_event      = esp32_log_event_cb,
        .telemetry_emit = esp32_telemetry_emit_cb,
    };
    thermal_status_t init_s = thermal_core_init(&core, &G_THERMAL_CFG, &cb);
    if (init_s != THERMAL_OK) {
        ESP_LOGE(TAG, "thermal_core_init failed: %d", (int)init_s);
        return;
    }

    /* Cached sensor reading: refreshed once per second.  Between
     * conversions every tick re-uses the last valid value. */
    int32_t cached_temp_mc = INT32_MIN;
    uint8_t cached_valid   = 0;

    uint32_t now_ms        = 0;
    int      ticks_since_read = 10;     /* force a read on tick 0 */
    const uint16_t dt_ms   = G_THERMAL_CFG.control_period_ms;

    for (;;) {
        int64_t t0_us = esp_timer_get_time();

        /* === Step 1: refresh sensor at 1 Hz cadence ============= */
        if (sensor_ok && ticks_since_read >= 10) {
            int32_t temp_mc;
            if (bsp_esp32_sensor_read_mc(&temp_mc) == 0) {
                cached_temp_mc = temp_mc;
                cached_valid   = 1;
            } else {
                cached_valid = 0;
            }
            ticks_since_read = 0;
        }
        ticks_since_read++;

        /* === Step 2: build input snapshot ====================== */
        thermal_sample_t samples[THERMAL_MAX_SAMPLES_PER_SNAPSHOT];
        uint8_t n = 0;

        samples[n].id           = G_THERMAL_CFG.sensors[0].id;
        samples[n].kind         = THERMAL_SAMPLE_TEMP_MC;
        samples[n].sample_ts_ms = now_ms;
        samples[n].value        = cached_temp_mc;
        samples[n].valid        = cached_valid;
        samples[n].quality      = 0;
        n++;

        uint32_t ticks = bsp_esp32_tach_read_ticks_delta();
        samples[n].id           = G_THERMAL_CFG.actuators[0].id;
        samples[n].kind         = THERMAL_SAMPLE_TACH_RPM;
        samples[n].sample_ts_ms = now_ms;
        samples[n].value        = (int32_t)(ticks * 30u);
        samples[n].valid        = 1;
        samples[n].quality      = 0;
        n++;

        thermal_input_snapshot_t snap = {
            .now_ms       = now_ms,
            .samples      = samples,
            .sample_count = n,
        };

        /* === Step 3: tick the core ============================ */
        thermal_output_frame_t out;
        memset(&out, 0, sizeof(out));
        (void)thermal_core_step(&core, &snap, &out);

        /* === Step 4: apply actuator commands ================== */
        for (uint8_t i = 0; i < out.actuator_cmd_count; i++) {
            if (out.actuator_cmds[i].actuator_id ==
                G_THERMAL_CFG.actuators[0].id) {
                bsp_esp32_pwm_set_duty(out.actuator_cmds[i].duty_0_255);
            }
        }

        /* === Step 5: once per second print the status line ==== */
        if (ticks_since_read == 1) {     /* just refreshed */
            int32_t temp_mc = esp32_callbacks_last_zone_temp_mc(0);
            int32_t pwm_val = esp32_callbacks_last_actuator_pwm(0);
            if (cached_valid) {
                printf("T=%6.2f C  duty=%3" PRId32 "/255 (%3" PRId32
                       "%%)  tach=%4" PRIu32 " ticks/s (~%4" PRIu32 " RPM)\n",
                       (double)temp_mc / 1000.0,
                       pwm_val, (pwm_val * 100) / 255,
                       ticks, ticks * 30u);
            } else {
                printf("T=  ERR    duty=%3" PRId32 "/255 (%3" PRId32
                       "%%)  tach=%4" PRIu32 " ticks/s (~%4" PRIu32 " RPM)\n",
                       pwm_val, (pwm_val * 100) / 255,
                       ticks, ticks * 30u);
            }
        }

        /* Pace the next tick. */
        now_ms += dt_ms;
        int64_t elapsed_us = esp_timer_get_time() - t0_us;
        int64_t remaining_us = (int64_t)dt_ms * 1000 - elapsed_us;
        if (remaining_us > 0) {
            vTaskDelay(pdMS_TO_TICKS(remaining_us / 1000));
        }
    }
}

#endif /* mode dispatch */

void app_main(void)
{
#if defined(THERMALCORE_MODE_HIL_PERIPHERAL)
    app_main_hil_peripheral();
#elif defined(THERMALCORE_MODE_REPLAY_STANDALONE)
    app_main_replay();
#else
    app_main_standalone();
#endif
}
